// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationRequest) Reset()         { *m = ValidationRequest{} }
func (m *ValidationRequest) String() string { return proto.CompactTextString(m) }
func (*ValidationRequest) ProtoMessage()    {}
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *ValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationRequest.Unmarshal(m, b)
}
func (m *ValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationRequest.Marshal(b, m, deterministic)
}
func (m *ValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationRequest.Merge(m, src)
}
func (m *ValidationRequest) XXX_Size() int {
	return xxx_messageInfo_ValidationRequest.Size(m)
}
func (m *ValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationRequest proto.InternalMessageInfo

func (m *ValidationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ValidationResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationResponse) Reset()         { *m = ValidationResponse{} }
func (m *ValidationResponse) String() string { return proto.CompactTextString(m) }
func (*ValidationResponse) ProtoMessage()    {}
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *ValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationResponse.Unmarshal(m, b)
}
func (m *ValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationResponse.Marshal(b, m, deterministic)
}
func (m *ValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationResponse.Merge(m, src)
}
func (m *ValidationResponse) XXX_Size() int {
	return xxx_messageInfo_ValidationResponse.Size(m)
}
func (m *ValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationResponse proto.InternalMessageInfo

func (m *ValidationResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type UserCredential struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredential) Reset()         { *m = UserCredential{} }
func (m *UserCredential) String() string { return proto.CompactTextString(m) }
func (*UserCredential) ProtoMessage()    {}
func (*UserCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *UserCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredential.Unmarshal(m, b)
}
func (m *UserCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredential.Marshal(b, m, deterministic)
}
func (m *UserCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredential.Merge(m, src)
}
func (m *UserCredential) XXX_Size() int {
	return xxx_messageInfo_UserCredential.Size(m)
}
func (m *UserCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredential.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredential proto.InternalMessageInfo

func (m *UserCredential) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCredential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticationResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResponse) Reset()         { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()    {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *AuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResponse.Unmarshal(m, b)
}
func (m *AuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResponse.Merge(m, src)
}
func (m *AuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResponse.Size(m)
}
func (m *AuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResponse proto.InternalMessageInfo

func (m *AuthenticationResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidationRequest)(nil), "protobuf.ValidationRequest")
	proto.RegisterType((*ValidationResponse)(nil), "protobuf.ValidationResponse")
	proto.RegisterType((*UserCredential)(nil), "protobuf.UserCredential")
	proto.RegisterType((*AuthenticationResponse)(nil), "protobuf.AuthenticationResponse")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0xe2, 0x8c, 0x8f, 0x31, 0x34, 0xc8, 0x2c, 0x9d, 0x87, 0xd1, 0x93, 0x7a, 0xe8,
	0x70, 0x5e, 0xbd, 0xa8, 0xec, 0xa0, 0xc7, 0x80, 0x9e, 0x04, 0xc9, 0xd6, 0x67, 0x17, 0x68, 0x9b,
	0x9a, 0xa4, 0x8a, 0x7f, 0x89, 0xff, 0xae, 0x24, 0xe9, 0xec, 0x8a, 0x65, 0xa7, 0xf0, 0xbd, 0xf7,
	0x7b, 0xef, 0xcb, 0xfb, 0x60, 0xa8, 0x57, 0x6b, 0x2c, 0x78, 0x52, 0x29, 0x69, 0x24, 0x25, 0xee,
	0x59, 0xd6, 0xef, 0xd1, 0x24, 0x93, 0x32, 0xcb, 0x71, 0xb6, 0x29, 0xcc, 0xb0, 0xa8, 0xcc, 0xb7,
	0xc7, 0xe2, 0x4b, 0x38, 0x79, 0xe1, 0xb9, 0x48, 0xb9, 0x11, 0xb2, 0x64, 0xf8, 0x51, 0xa3, 0x36,
	0xf4, 0x14, 0x0e, 0xb0, 0xe0, 0x22, 0x0f, 0x83, 0x69, 0x70, 0x71, 0xc4, 0xbc, 0x88, 0xaf, 0x80,
	0x6e, 0xa3, 0xba, 0x92, 0xa5, 0x46, 0xcb, 0x7e, 0xda, 0xaa, 0x63, 0x09, 0xf3, 0x22, 0xbe, 0x87,
	0xd1, 0xb3, 0x46, 0xf5, 0xa0, 0x30, 0xc5, 0xd2, 0x08, 0x9e, 0xf7, 0xef, 0xa4, 0x11, 0x90, 0x8a,
	0x6b, 0xfd, 0x25, 0x55, 0x1a, 0xee, 0xb9, 0xc6, 0x9f, 0x8e, 0xaf, 0x61, 0x7c, 0x57, 0x9b, 0xb5,
	0x9d, 0x5f, 0x75, 0x3d, 0xcf, 0xe0, 0xb0, 0xd6, 0xa8, 0xde, 0x1a, 0xd7, 0x7d, 0x36, 0xb0, 0xf2,
	0x31, 0x9d, 0xff, 0x04, 0x70, 0x6c, 0x7d, 0x19, 0x66, 0x42, 0x1b, 0xe5, 0xa6, 0xe8, 0x02, 0x48,
	0xf3, 0x6f, 0xa4, 0x93, 0x64, 0x93, 0x42, 0xf2, 0xef, 0xec, 0xe8, 0xbc, 0xbf, 0xd9, 0x98, 0xde,
	0x02, 0xf1, 0x6b, 0x51, 0xd1, 0xb0, 0x25, 0xbb, 0x67, 0x46, 0xe3, 0xc4, 0xa7, 0xdd, 0x02, 0x0b,
	0x9b, 0xf6, 0xfc, 0x15, 0x46, 0xdd, 0x63, 0xe8, 0x13, 0x0c, 0xb7, 0x2a, 0xb8, 0x63, 0xe7, 0xb4,
	0xed, 0xf4, 0x07, 0xb2, 0x1c, 0x38, 0xe0, 0xe6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x9b, 0x12,
	0x1e, 0x03, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserRegistrationClient is the client API for UserRegistration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserRegistrationClient interface {
	Validate(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
	Register(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userRegistrationClient struct {
	cc *grpc.ClientConn
}

func NewUserRegistrationClient(cc *grpc.ClientConn) UserRegistrationClient {
	return &userRegistrationClient{cc}
}

func (c *userRegistrationClient) Validate(ctx context.Context, in *ValidationRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, "/protobuf.UserRegistration/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRegistrationClient) Register(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/protobuf.UserRegistration/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRegistrationServer is the server API for UserRegistration service.
type UserRegistrationServer interface {
	Validate(context.Context, *ValidationRequest) (*ValidationResponse, error)
	Register(context.Context, *UserCredential) (*empty.Empty, error)
}

// UnimplementedUserRegistrationServer can be embedded to have forward compatible implementations.
type UnimplementedUserRegistrationServer struct {
}

func (*UnimplementedUserRegistrationServer) Validate(ctx context.Context, req *ValidationRequest) (*ValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (*UnimplementedUserRegistrationServer) Register(ctx context.Context, req *UserCredential) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterUserRegistrationServer(s *grpc.Server, srv UserRegistrationServer) {
	s.RegisterService(&_UserRegistration_serviceDesc, srv)
}

func _UserRegistration_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRegistrationServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserRegistration/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRegistrationServer).Validate(ctx, req.(*ValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRegistration_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRegistrationServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.UserRegistration/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRegistrationServer).Register(ctx, req.(*UserCredential))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRegistration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.UserRegistration",
	HandlerType: (*UserRegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _UserRegistration_Validate_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserRegistration_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	Authenticate(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*AuthenticationResponse, error)
}

type authenticationClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationClient(cc *grpc.ClientConn) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Authenticate(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Authentication/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	Authenticate(context.Context, *UserCredential) (*AuthenticationResponse, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) Authenticate(ctx context.Context, req *UserCredential) (*AuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Authentication/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Authenticate(ctx, req.(*UserCredential))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Authentication_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
